name: SimpleVeinEnchants
version: 1.1.1
main: dev.xeaf.simpleveinenchants.SimpleVeinEnchants
bootstrapper: dev.xeaf.simpleveinenchants.SimpleVeinEnchantsBootstrap
api-version: '26.1'
folia-supported: true
